apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-vite-app
  labels:
    app: react-vite-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-vite-app
  template:
    metadata:
      labels:
        app: react-vite-app
    spec:
      containers:
      - name: react-vite-app
        # Jenkins will inject the proper ECR image tag here
        image: 957411488827.dkr.ecr.ap-south-1.amazonaws.com/react-vite-app:13
        ports:
        - containerPort: 80
        imagePullPolicy: Always